[package]
name = "yep_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.2.0"
chumsky = { git = "https://github.com/zesterer/chumsky" }
logos = "0.12.1"
snailquote = "0.3.1"
